#!/usr/bin/env php
<?php
/**
 * main entry point for starting a Cuke4Php wire server
 * @package Cuke4Php
 */

require_once 'PHPUnit/Autoload.php';
/**
 * load the Cuke4Php server
 */
require_once dirname(__FILE__) . "/../lib/Cuke4Php.php";
$aOptions = getopt("p:");
$oServer = new Cuke4Php(realpath($argv[$argc-1]), $aOptions['p']);
$oServer->run();
?>
